# Generated by Django 4.2.5 on 2023-09-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MusicTitle', models.CharField(max_length=255)),
                ('ArtistName', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=100)),
            ],
        ),
    ]
